### ISSUE TITLE
怎么不执行下载任务

### ISSUE THREAD

**Issue by qh1234qwer** [xwdz/QuietDownload#12]

**Comment by xwdz** [comment]
请提供更多详细信息。
 确认url是否能正常下载

**Comment by qh1234qwer** [comment]
我直接用你demo里面提供的下载地址










------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xwcc"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 下午4:27
收件人: "xwdz/QuietDownload"<QuietDownload@noreply.github.com&gt;; 
抄送: "·········"<1552998300@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xwdz/QuietDownload] 怎么不执行下载任务 (#12)





 
请提供更多详细信息。
 确认url是否能正常下载

**Comment by xwdz** [comment]
有些下载地址可能已经失效。跟换可用地址即可

**Comment by qh1234qwer** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xwcc"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 下午4:27
收件人: "xwdz/QuietDownload"<QuietDownload@noreply.github.com&gt;; 
抄送: "·········"<1552998300@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xwdz/QuietDownload] 怎么不执行下载任务 (#12)





 
请提供更多详细信息。
 确认url是否能正常下载

**Comment by qh1234qwer** [comment]
麻烦你看一下我的集成方式






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xwdz/QuietDownload"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月18日(星期五) 下午4:27
收件人:&nbsp;"xwdz/QuietDownload"<QuietDownload@noreply.github.com&gt;;
抄送:&nbsp;"·········"<1552998300@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xwdz/QuietDownload] 怎么不执行下载任务 (#12)





 
请提供更多详细信息。
 确认url是否能正常下载

**Comment by qh1234qwer** [comment]
application里面我已经初始化了

**Comment by qh1234qwer** [comment]
哥们看到回一个，照着集成文档集成不执行下载任务】

**Comment by xwdz** [comment]
1. 我并没有看到你贴的图以及log跟集成方式
2. 检查是否添加了网络权限
3. 确认当前网络

**Comment by qh1234qwer** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xwcc"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 下午4:43
收件人: "xwdz/QuietDownload"<QuietDownload@noreply.github.com&gt;; 
抄送: "·········"<1552998300@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xwdz/QuietDownload] 怎么不执行下载任务 (#12)





  
我并没有看到你贴的图以及log跟集成方式
 
检查是否添加了网络权限
 
确认当前网络

**Comment by qh1234qwer** [comment]
权限肯定有，网络没有问题








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xwcc"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 下午4:43
收件人: "xwdz/QuietDownload"<QuietDownload@noreply.github.com&gt;; 
抄送: "·········"<1552998300@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xwdz/QuietDownload] 怎么不执行下载任务 (#12)





  
我并没有看到你贴的图以及log跟集成方式
 
检查是否添加了网络权限
 
确认当前网络

**Comment by qh1234qwer** [comment]
权限有，网络也能用












------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xwcc"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 下午4:43
收件人: "xwdz/QuietDownload"<QuietDownload@noreply.github.com&gt;; 
抄送: "·········"<1552998300@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xwdz/QuietDownload] 怎么不执行下载任务 (#12)





  
我并没有看到你贴的图以及log跟集成方式
 
检查是否添加了网络权限
 
确认当前网络

**Comment by xwdz** [comment]
提供日志
