### ISSUE TITLE
多任务下载不了的

### ISSUE THREAD

**Issue by yanpengqing** [xwdz/QuietDownload#13]
亲测，
多任务只有第一个有效，其它的都下载不了

**Comment by xwdz** [comment]
请用可用的下载链接替换项目里面原有的得链接；
simple里面得下载链接已经失效

**Comment by yanpengqing** [comment]
> 请用可用的下载链接替换项目里面原有的得链接；
> simple里面得下载链接已经失效

跟连接无关的，同一个url，第一个成功，第二个失败

**Comment by yanpengqing** [comment]
> 请用可用的下载链接替换项目里面原有的得链接；
> simple里面得下载链接已经失效

我找到原因了，默认多任务时间间隔是800毫秒，如果两次任务的时间间隔小于这个值就不会开启新任务下载
