### ISSUE TITLE
DownService

### ISSUE THREAD

**Issue by malonecoder** [xwdz/QuietDownload#8]
您好 为什么取消在service中下载呢， 还有一个问题就是有的时候一个下载资源  只读取了2000多个字节就直接退出不下载了 而且每次都是那个固定值2181好象是    您这能分析出什么原因吗 换个网络啥的有时候能解决这个问题

**Comment by xwdz** [comment]
@malonecoder  取消使用service下载，是考虑到Android O P Q版本上不能使用后台线程。

**Comment by malonecoder** [comment]
又遇到这个问题了 固定值是2281   两个都是9.0版本 一个华为 一个模拟器  ，下载场景是应用刚启动的时候会下载三个广告图片 每个图片大小1M左右，三个同时下载，中间隔了一秒钟~  三个都直接返回2281 的in.read(buffer)就=-1了

**Comment by xwdz** [comment]
@malonecoder 使用的QuietDownload版本是？ 
你三张图片的链接给我提供下，我尝试复现下

**Comment by malonecoder** [comment]
哇 回复这么快 谢谢~我是直接下载拷贝到项目里的 
http://test.static.lvyuetravel.com/cms/material/20191211/c5beec37-d0da-49b6-92f8-573a8b3ba001.png
http://test.static.lvyuetravel.com/cms/material/20191213/8c6e282d-a727-44a1-8e63-979107b4cf84.jpg
http://test.static.lvyuetravel.com/cms/material/20191213/8c6e282d-a727-44a1-8e63-979107b4cf84.jpg

**Comment by xwdz** [comment]
@malonecoder 收到。我先复现下
如果你着急的话你可以试试修改成downloadConfig.setMaxDownloadTasks(1);

**Comment by malonecoder** [comment]
已经设置成1了 downThread也设置成1了 哈哈 下完第一个才下的第二个  能加您个联系方式吗

**Comment by xwdz** [comment]
@malonecoder 👍 
好 vx:aidongtian8
